apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-customers-deployment
  labels:
    app: api-customers
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-customers
  template:
    metadata:
      labels:
        app: api-customers
    spec:
      containers:
      - name: api-customers
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9119
          name: spring-port
